#!/bin/sh
# T3 local ACP entry, using a current-runtime profile with existing model routes.
export PATH="/Users/yu/.npm-global/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
exec /Users/yu/.npm-global/bin/dsh --profile t3-acp "$@"
